on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build base verifier docker image
      run: docker build -t verifier .
    - name: Run tests
      run: docker run verifier bash -c "mkdir -p ../data/ && wget -c http://storage.googleapis.com/feature_dataset/renditions-nano.tar.gz -O - | tar -xz -C ../data/ && python -m pytest testing/tests"
    - name: Login to docker
      run: docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}
    - name: Tag latest verifier image
    - run: docker tag verifier livepeer/verifier:latest
    - name: Push latest verifier image
      run: docker push livepeer/verifier:latest
    - name: Build and push verifier-api Docker image
      uses: docker/build-push-action@v1.1.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: livepeer/verifier-api
        dockerfile: Dockerfile-api
        tag_with_ref: true
