on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install PyEnv
      run: curl https://pyenv.run | bash
    - name: Restart shell
      run: exec $SHELL
    - name: Install required Python version
      run: pyenv init && pyenv install -v 3.6.7
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Download and extract nano dataset for tests
      run: mkdir -p ../data/ && wget -c http://storage.googleapis.com/feature_dataset/renditions-nano.tar.gz -O - | tar -xz -C ../data/
    - name: Run tests
      run: python3 -m pytest testing/tests/
    - name: Build and push latest verifier Docker image
      uses: docker/build-push-action@v1.1.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: livepeer/verifier
        tags: latest
        cache_froms: livepeer/verifier:latest
    - name: Build and push verifier-api Docker image
      uses: docker/build-push-action@v1.1.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: livepeer/verifier-api
        dockerfile: Dockerfile-api
        tag_with_ref: true
